baseURL = "http://example.org/"
languageCode = "en-us"
title = "Alex Ma"
theme = "hugo-theme-basic"
googleAnalytics = "UA-XXXXXXXXX-X"
enableEmoji = true

[params]
  titleEmoji = ":tada::tada::tada:"

[Permalinks]
  post = "post/:slug"

[[params.menu]]
  name = "blog"
  url = "posts/"

[[params.menu]]
  name = "about"
  url = "about/"
